# Site settings
title: Real Story
email: ""
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  RealStory
beianhao: ""
# Build settings
markdown: kramdown
